### ISSUE TITLE
Import error: No module found

### ISSUE THREAD

**Issue by ans-qureshi** [tu-rbo/differentiable-particle-filters#1]
I have followed all the steps and installed all the dependencies as mentioned here. When I run the command "python3 simple.py" this shows up 
```
Traceback (most recent call last):
  File "simple.py", line 3, in <module>
    from methods.dpf import DPF
ImportError: No module named 'method'
```
I'm facing this same issue when I try to run every other .py file. Is it some dependency that I'm missing? 
Before this I faced the error "illegal instruction (core dumped)" however that was resolved by downgrading Tensorflow to v1.5.

**Comment by divyamrast** [comment]
Did you have a look at the 'Usage' part in README?

**Comment by romi-seecs** [comment]
Yes. Is this correct?
echo $PYTHONPATH
/opt/ros/kinetic/lib/python2.7/dist-packages:/home/romi/differentiable-particle-filters/experiments

**Comment by ans-qureshi** [comment]
Yes. Is this correct?

echo $PYTHONPATH
`/opt/ros/kinetic/lib/python2.7/dist-packages:/home/romi/differentiable-particle-filters`

**Comment by divyamrast** [comment]
No.

Your echo $PYTHONPATH should look like this:
/opt/ros/kinetic/lib/python2.7/dist-packages:../

And then you should be able to execute simple.py from the folder 'experiments'.

**Comment by ans-qureshi** [comment]
Perfect :+1:
