### ISSUE TITLE
Dataset link expires

### ISSUE THREAD

**Issue by KawhiZhao** [tu-rbo/differentiable-particle-filters#7]
Hi, the dataset is not available now. Could you please give a new link

**Comment by leekt0124** [comment]
I have the same issue when downloading the dataset.

**Comment by manuelbaum** [comment]
I updated the link in the setup file:
https://depositonce.tu-berlin.de/bitstreams/fe02c1e0-64d9-4a92-ac4d-a8a0ef455c8f/download
